# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'downloadTool.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setMinimumSize(QtCore.QSize(700, 500))
        MainWindow.setMaximumSize(QtCore.QSize(700, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(700, 500))
        self.centralwidget.setMaximumSize(QtCore.QSize(700, 500))
        self.centralwidget.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(245, 213, 172, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButtonMp3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonMp3.setMinimumSize(QtCore.QSize(100, 30))
        self.radioButtonMp3.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButtonMp3.setFont(font)
        self.radioButtonMp3.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-radius: 15px;")
        self.radioButtonMp3.setObjectName("radioButtonMp3")
        self.verticalLayout.addWidget(self.radioButtonMp3)
        self.radioButtonMp4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonMp4.setMinimumSize(QtCore.QSize(100, 30))
        self.radioButtonMp4.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButtonMp4.setFont(font)
        self.radioButtonMp4.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-radius: 15px;")
        self.radioButtonMp4.setObjectName("radioButtonMp4")
        self.verticalLayout.addWidget(self.radioButtonMp4)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setMinimumSize(QtCore.QSize(530, 60))
        self.textEdit_2.setMaximumSize(QtCore.QSize(530, 60))
        self.textEdit_2.setSizeIncrement(QtCore.QSize(250, 0))
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_4.addWidget(self.textEdit_2, 2, 0, 1, 1)
        self.labelDeger = QtWidgets.QLabel(self.centralwidget)
        self.labelDeger.setMinimumSize(QtCore.QSize(530, 0))
        self.labelDeger.setMaximumSize(QtCore.QSize(530, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelDeger.setFont(font)
        self.labelDeger.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelDeger.setObjectName("labelDeger")
        self.gridLayout_4.addWidget(self.labelDeger, 1, 0, 1, 1)
        self.pushButtonAra = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAra.setMinimumSize(QtCore.QSize(30, 80))
        self.pushButtonAra.setMaximumSize(QtCore.QSize(30, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAra.setFont(font)
        self.pushButtonAra.setObjectName("pushButtonAra")
        self.gridLayout_4.addWidget(self.pushButtonAra, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem, 2, 0, 1, 1)
        self.frameDownload = QtWidgets.QFrame(self.centralwidget)
        self.frameDownload.setMinimumSize(QtCore.QSize(300, 300))
        self.frameDownload.setMaximumSize(QtCore.QSize(300, 300))
        self.frameDownload.setStyleSheet("QFrame{\n"
"    border-radius:150px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:270.119, stop:0 rgba(255, 255, 255, 255), stop:0.457711 rgba(207, 255, 207, 255), stop:0.517413 rgba(80, 255, 80, 255), stop:1 rgba(0, 255, 0, 255));\n"
"\n"
"}\n"
"")
        self.frameDownload.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDownload.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDownload.setObjectName("frameDownload")
        self.frame_2 = QtWidgets.QFrame(self.frameDownload)
        self.frame_2.setGeometry(QtCore.QRect(20, 20, 260, 260))
        self.frame_2.setMaximumSize(QtCore.QSize(260, 260))
        self.frame_2.setSizeIncrement(QtCore.QSize(260, 260))
        self.frame_2.setStyleSheet("QFrame{\n"
"    border-radius:130px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.labelOutput = QtWidgets.QLabel(self.frame_2)
        self.labelOutput.setGeometry(QtCore.QRect(54, 85, 151, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelOutput.setFont(font)
        self.labelOutput.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.labelOutput.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelOutput.setText("")
        self.labelOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOutput.setObjectName("labelOutput")
        self.gridLayout_10.addWidget(self.frameDownload, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setStyleSheet("")
        self.frame_5.setObjectName("frame_5")
        self.label_image = QtWidgets.QLabel(self.frame_5)
        self.label_image.setGeometry(QtCore.QRect(20, 10, 320, 240))
        self.label_image.setMinimumSize(QtCore.QSize(320, 240))
        self.label_image.setMaximumSize(QtCore.QSize(320, 240))
        self.label_image.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.labelSarkiAdi = QtWidgets.QLabel(self.frame_5)
        self.labelSarkiAdi.setGeometry(QtCore.QRect(24, 260, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelSarkiAdi.setFont(font)
        self.labelSarkiAdi.setText("")
        self.labelSarkiAdi.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSarkiAdi.setObjectName("labelSarkiAdi")
        self.gridLayout_10.addWidget(self.frame_5, 0, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_indir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_indir.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_indir.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_indir.setFont(font)
        self.pushButton_indir.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_indir.setObjectName("pushButton_indir")
        self.horizontalLayout_2.addWidget(self.pushButton_indir)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout_10.addLayout(self.horizontalLayout_2, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButtonMp3.setText(_translate("MainWindow", "MP3"))
        self.radioButtonMp4.setText(_translate("MainWindow", "MP4"))
        self.labelDeger.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8f8f8f;\">Video linkini giriniz...</span></p></body></html>"))
        self.pushButtonAra.setText(_translate("MainWindow", "A\n"
"R\n"
"A"))
        self.pushButton_indir.setText(_translate("MainWindow", "INDIR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
